{...}:
{
  imports = [
    ./bibata.nix
    ./bluetooth.nix
    ./bootloader.nix
    ./chromium.nix
    ./cli-tools.nix
    ./fcitx.nix
    ./firefox.nix
    ./helix.nix
    ./librewolf.nix
    ./media.nix
    ./nvidia.nix
    ./plasma.nix
    ./printing.nix
    ./swap.nix
    ./sound.nix
    ./networking.nix
    ./common.nix
    ./ssh.nix
    ./vesktop.nix
  ];
}
